### ISSUE TITLE
header

### ISSUE THREAD

**Issue by blender-girl** [Flix01/fbtBlend-Header-Only#4]
hi

Can I ask why blender 3.4 has in the header of a .blend file '304' instead of '340' ?
Because '304' seems to me 3.04 but '340' is 3.40 ?

see: https://fossies.org/linux/blender/doc/blender_file_format/mystery_of_the_blend.html

**Comment by Flix01** [comment]
Sure!

Well, from the link you posted:
```Version of Blender the file was created in; '254' means version 2.54```

So: '304' means version 3.04 and '340' means version 3.40.

From what I understand, "blender 3.4" means "blender 3.04".

Beside that, AFAIR, the version all the "Blender.h" files (like 304 in [this](https://github.com/Flix01/fbtBlend-Header-Only/blob/3e1b92b5f41f76420e0382aabef1821b3df63b3b/304/Blender.h#L5)) is autogenerated (that info is read from a .blend file), so it's not something that I can change.

Closing this as answered.

**Comment by blender-girl** [comment]
Yes, Blender 3.4.1 still gives "304" :) I think because there are only 3 digits and they can't change the convention for subversions.
And "3041" is not possible, there are only 3 digits

I was thinking a bit more about this.
Maybe "304" is used to have "some room" for when the version goes from 3.9 to 3.10? The "0" is a sort of place holder?
So then "309" becomes "310" because otherwise they can't fit it in 3 digits.
And they could not use "340" for now because then you can confuse this with "310" when 3.10 is released.

I don't find another explanation. You do?

**Comment by Flix01** [comment]
Yes, I think 304 means 3.04, so that 340 should be 3.40. And it's also a common general convention that the version 5.6 of a generic program is older than version 5.11 (so that 5.6 **always** means 5.06).

As far as the number of digits is concerned, a .blend file 3.04.X should still generate the same files (not only the same 3-digit version 304): "Blender.h" and "fbtBlend.h". That means that all Blender subversions (or minor versions) are not allowed to change the internal structures of their major versions.

**Comment by blender-girl** [comment]
But then I have a really tricky question: Blender 2.04 once existed :)
So what is 2.04 converted to the 3 digits?

**Comment by Flix01** [comment]
Maybe: 
Blender 2.04 (released 20-Aug-2003) = Blender 2.4 = 204
And:
Blender 2.40 (released 22-Dec-2005) = Blender 2.40 = 204

The zero in Blender 2.04 is optional and useful to avoid confusion between the two versions.
