### ISSUE TITLE
Missing License

### ISSUE THREAD

**Issue by was421** [Flix01/fbtBlend-Header-Only#5]
Hi could you please license this code so that I can use it?

the original gamekit was under MIT: https://code.google.com/archive/p/gamekit/

**Comment by Flix01** [comment]
Well, I keep the same original license for the modifications I've made.

However please note that:

- The license that appears at the top of these two files is kept intact. Please check:
[fbtBlend.h](https://github.com/gamekit-developers/gamekit/blob/74c896af5826ebe8fb72f2911015738f38ab7bb2/Tools/FileTools/FileFormats/Blend/fbtBlend.h#L1) from the original gamekit repository.
[fbtBlend.h](https://github.com/Flix01/fbtBlend-Header-Only/blob/398df0d5efd21eb656bc0907301ff7f149391eac/fbtBlend.h#L1) from this repository. Some lines below I added: ```Slightly modified by Flix01 (same license)```.

- The original fbtBlend inside gamekit was not header-only and needed the generated file [bfBlender.cpp](https://github.com/gamekit-developers/gamekit/blob/master/Tools/FileTools/FileFormats/Blend/Generated/bfBlender.cpp). Now that file has been embedded inside _fbtBlend.h_.

Now the problem with the license is that:
- _bfBlender.cpp_ (now embedded into _fbtBlend.h_) contains some binary data (I think that part is called the "dna", or something like that) extracted from a test .blend file.
- _Blender.h_ is also extracted from the same .blend file, but it's not a binary file.

So, actually, even if **_I did not introduce anything new_**, I'm not sure if this can really be used under MIT license.
What I mean is that our work is under the MIT license, but some necessary "glue" is taken from .blend files.

I'm not a lawyer, so I don't know what to say about this...

**Comment by Flix01** [comment]
> Any and all changes you made, you can 100% put under any license of your choosing.

Yes, my intent is to keep the same license as the original code (MIT as far as I know).

> Github has cool tool to help you [choose a license](https://choosealicense.com/). Gamekit (MIT) and Blender (GNU General Public License) both are permissive with proper attribution and you should be able to put anything permissive on here.
about that blob in [bfBlender.cpp](https://github.com/gamekit-developers/gamekit/blob/master/Tools/FileTools/FileFormats/Blend/Generated/bfBlender.cpp) isn't anything closed source or anything licensed differently. It looks to be the output from this function [makesdna.cc](https://github.com/blender/blender/blob/main/source/blender/makesdna/intern/makesdna.cc) that's either something incredibly smart or cursed (I'm not qualified to say which).

What I mean is that I'm not sure if the .blend file's (or the Blender source code?) license (GNU General Public License?) is compatible with the MIT license so that I could just forget it and use the MIT license...

...or if the MIT license is compatible with the .blend license (GNU General Public License?), so that I should release my changes under the .blend license instead.

Shouldn't we always use the most restrictive license?

P.S. In any case the (two) parts extracted from .blend files, now are generated by fbtBlendUpdater.cpp in this repository, a tool I made it for this purpose (AFAIR) some year ago.

**Comment by Flix01** [comment]
From https://www.blender.org/support/faq/

> ## [Can I license .blend files myself?](https://www.blender.org/support/faq/#using-blender-7)

> Yes. The output of Blender, in the form of .blend files, is considered program output, and the sole copyright of the user. The .blend file format only stores data definitions.
> In case you embed the .blend file with Python scripts, and the scripts provide bindings to other libraries or facilities, the next topic applies. [...]

So maybe, since we don't use scripts inside the .blend file we use for generating our source files, the extracted part of the .blend file (that is probably the "data definitions"-related stuff) can be released under any license.
This should allow us to extend the MIT license on all the files in the repository.

**Comment by was421** [comment]
Sure, all you would need to do is apply your own license (which based on the commits looks like you want the same type of license, MIT) and that would cover your contributions then making this repo usable to the masses.

**Comment by Flix01** [comment]
Actually I've discovered that:

Quote from [gamekit quick start guide](https://code.google.com/archive/p/gamekit/wikis/QuickstartGuide.wiki):
> Gamekit exclusively uses very permissive software licenses, either BSD, ZLib or MIT. Those licenses are great for development of commercial applications or when used with proprietary technology and platforms.

So, since the original license of _fbtBlend.h_ seems to be the Zlib License, I've used the same license.

Closing this.

**Comment by Flix01** [comment]
Please note however that the test files (C/C++ code) used to test the library still keep their own license (at the top of each). 
(AFAIR some of them are MIT licensed).
